### ISSUE TITLE
Implicit function declare problem when compiling zydis separately from zycore-c

### ISSUE THREAD

**Issue by yszhou2019** [zyantific/zydis#351]
Description: According to the installation method of libzydis official doc, using git clone --recursive libzydis can be installed normally.

Question: Due to various reasons, the two libs need to be compiled separately, that is, they are no longer through git clone --recursive, but cloned and compiled separately. At present, libzycore has been installed, and the cmk file of libzydis has been modified. The include and link paths of libzycore have been manually added into cmkfile of libzycore. The implicit function declare is encountered during the compilation process.

The cmk file changes as shown in the following:

> 
> if (ZYDIS_BUILD_SHARED_LIB)
>     add_library("Zydis" SHARED)
> else ()
>     add_library("Zydis" STATIC)
> endif ()
> 
> +include_directories("/Users/yszhou/.xmake/packages/z/zycore-c/v1.0.0/ebab6af9b833492aafd003a7740b9da8/include")
> +link_directories("/Users/yszhou/.xmake/packages/z/zycore-c/v1.0.0/ebab6af9b833492aafd003a7740b9da8/lib")
> 

After changing the cmk file, the compilation fails as shown:

> ➜  v3.2.1 xrepo install zydis
> note: install or modify (m) these packages (pass -y to skip confirm)?
> in mine:
>   -> zydis v3.2.1
> please input: y (y/n/m)
> y
>   => install zydis v3.2.1 .. failed
> 
> In file included from /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/src/FormatterBuffer.c:27:
> /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/include/Zydis/Internal/String.h:375:46: error: implicit declaration of function 'ZyanAbsI64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
> In file included from /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/src/String.c:27:
> /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/include/Zydis/Internal/String.h:375:46        return ZydisStringAppendDecU(string, ZyanAbsI64(value), padding_length,
> :                                              ^error: implicit declaration of function 'ZyanAbsI64' is invalid in C99 [-Werror,-Wimplicit-function-declar[ 56%] Building C object CMakeFiles/Zydis.dir/src/FormatterBase.c.o
> e), padding_length,
>                                              ^
> /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/include/Zydis/Internal/String.h/Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/source/include/Zydis/Internal/String.h:444:46: error: implicit declaration of function 'ZyanAbsI64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
> :444:46: error: implicit declaration of function 'ZyanAbsI64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>         return ZydisStringAppendHexU(string, ZyanAbsI64(value), padding_length, uppercase,
>                                              ^
>         return ZydisStringAppendHexU(string, ZyanAbsI64(value), padding_length, uppercase,
>                                              ^
> 2 errors generated.
> 2 errors generated.
> make[2]: *** [CMakeFiles/Zydis.dir/src/FormatterBuffer.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> if you want to get more verbose errors, please see:
>   -> /Users/yszhou/.xmake/cache/packages/2206/z/zydis/v3.2.1/installdir.failed/logs/install.txt

**Comment by flobernd** [comment]
Like I said in the other issue, please make sure to always use the correct Zycore version 🙂 This function got added in the bleeding edge version of Zycore (used by the currently bleeding edge Zydis `master` branch). It's not included in Zycore v1.0.0 or v1.1.0 yet. It will be part of the next release Zycore v1.2.0 for Zydis v4.0.0.

**Comment by yszhou2019** [comment]
> 

Get it! Thank you!😘
I will try again. Hope this problem can be resolved

**Comment by yszhou2019** [comment]
Yes, zydis v3.2.1 works fine with zycore v1.1.0.
This problem is fixed.
Thank you ~
