### ISSUE TITLE
Compile error: a label can only be part of a statement

### ISSUE THREAD

**Issue by qiuyuX** [zyantific/zydis#75]
I had compilation error when build the master branch. My GCC version is "cc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609". Below is the error message.

[ 22%] Building C object CMakeFiles/Zydis.dir/src/Utils.c.o
In file included from /home/nature/Software/zydis/include/Zydis/Utils.h:35:0,
                 from /home/nature/Software/zydis/src/Utils.c:28:
/home/nature/Software/zydis/src/Utils.c: In function ‘ZydisGetInstructionSegments’:
/home/nature/Software/zydis/dependencies/zycore/include/Zycore/Defines.h:192:29: error: a label can only be part of a statement and a declaration is not a statement
define ZYAN_FALLTHROUGH __attribute__ ((fallthrough))
                             ^
/home/nature/Software/zydis/src/Utils.c:251:13: note: in expansion of macro ‘ZYAN_FALLTHROUGH’
             ZYAN_FALLTHROUGH;
             ^
/home/nature/Software/zydis/src/Utils.c:251:13: warning: empty declaration
In file included from /home/nature/Software/zydis/include/Zydis/Utils.h:35:0,
                 from /home/nature/Software/zydis/src/Utils.c:28:
/home/nature/Software/zydis/dependencies/zycore/include/Zycore/Defines.h:192:29: error: a label can only be part of a statement and a declaration is not a statement
define ZYAN_FALLTHROUGH __attribute__ ((fallthrough))
                             ^
/home/nature/Software/zydis/src/Utils.c:253:13: note: in expansion of macro ‘ZYAN_FALLTHROUGH’
             ZYAN_FALLTHROUGH;

**Comment by athre0z** [comment]
Hm, looks like `__attribute__ ((fallthrough))` was only introduced in GCC 7. I'll have to add a check on the compiler version. Thanks for the report!

**Comment by athre0z** [comment]
Should be fixed in https://github.com/zyantific/zydis/commit/a4619e31e5ea649d6f943291bde2496219e32728, it now works well in my Ubuntu 16.04 docker container!
